/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LanguageRouteImport } from './routes/$language'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LanguageViewStyleRouteImport } from './routes/$language_.view.$style'

const LanguageRoute = LanguageRouteImport.update({
  id: '/$language',
  path: '/$language',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageViewStyleRoute = LanguageViewStyleRouteImport.update({
  id: '/$language_/view/$style',
  path: '/$language/view/$style',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$language': typeof LanguageRoute
  '/$language/view/$style': typeof LanguageViewStyleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$language': typeof LanguageRoute
  '/$language/view/$style': typeof LanguageViewStyleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$language': typeof LanguageRoute
  '/$language_/view/$style': typeof LanguageViewStyleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$language' | '/$language/view/$style'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$language' | '/$language/view/$style'
  id: '__root__' | '/' | '/$language' | '/$language_/view/$style'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LanguageRoute: typeof LanguageRoute
  LanguageViewStyleRoute: typeof LanguageViewStyleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$language': {
      id: '/$language'
      path: '/$language'
      fullPath: '/$language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$language_/view/$style': {
      id: '/$language_/view/$style'
      path: '/$language/view/$style'
      fullPath: '/$language/view/$style'
      preLoaderRoute: typeof LanguageViewStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LanguageRoute: LanguageRoute,
  LanguageViewStyleRoute: LanguageViewStyleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
